# Generated by Django 4.1.2 on 2022-10-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='dept',
            field=models.CharField(default='Not Assigned', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(default='Not Assigned', max_length=100),
        ),
    ]
